# Generated by Django 3.1 on 2020-10-10 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20201010_0936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='listings',
        ),
    ]
