# Generated by Django 3.1 on 2020-11-14 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_auto_20201106_0842'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
    ]
