# Generated by Django 3.1 on 2020-10-10 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_remove_user_listings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
