# Generated by Django 3.1 on 2020-11-08 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_conversation_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='recipient_has_unread_messages',
        ),
        migrations.AddField(
            model_name='conversation',
            name='recipient_1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='conversation_recipient1', to='auctions.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conversation',
            name='recipient_2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='conversation_recipient2', to='auctions.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='recipient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_messages', to='auctions.user'),
            preserve_default=False,
        ),
    ]
