# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python applications

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  airline_app:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./django/airline

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install --user django
    - name: Run unit tests
      run: |
        python manage.py test
        
  simple-counter-app:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./django/selenium

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run e2e tests
      run: |
        google-chrome --version
        echo $CHROMEWEBDRIVER
        python test.py
